### ISSUE TITLE
[QUESTION] is that possible to use it with node 12?

### ISSUE THREAD

**Issue by LeonardoRick** [formcrafts/embed#1]
Im trying to use the package with a node 12 project. Is that possible?

![image](https://github.com/user-attachments/assets/1285c089-e057-4fd8-82c6-30209fd2d9b7)

```bash
 ERROR  Failed to compile with 1 error                                                                                                                                                         11:02:54 AM

 error  in ./node_modules/@formcrafts/embed/lib/embed.umd.js

Module parse failed: Unexpected token (19:21)

You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| 
|     class Drawer {
>         drawerElement;
|         options;
|         constructor(drawerElement, options) {

 @ ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/views/Detail.vue?vue&type=script&lang=js& 219:0-48
 @ ./src/views/Detail.vue?vue&type=script&lang=js&
 @ ./src/views/Detail.vue
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi ./node_modules/systemjs-webpack-interop/resource-query-public-path?systemjsModuleName=%40unbabel%2Ftranslations-auditing&rootDirectoryLevel=1 (webpack)-dev-server/client?http://10.30.84.21:8098&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.js
```

**Comment by nCrafts** [comment]
Please try using the 1.0.20-rc.0 version and let me know if the issue persists. If it does, please share your code or other steps to replicate the issue.

**Comment by LeonardoRick** [comment]
Hey @nCrafts thanks a lot for the response! It worked in a way that I could compile the code :)

The problem now is that the form is opening without the filled information

|Code|Form|
|--|--|
|![image](https://github.com/user-attachments/assets/bde83e43-7402-445d-bcd6-2332087654d6)|![image](https://github.com/user-attachments/assets/dad391b5-cbca-471d-8aca-c4d9e7744915)|

I noticed that the created `iframe` do not have the query params on its `src` url so I'm wondering where are this values stored 🤔 

![image](https://github.com/user-attachments/assets/ca530924-e324-47aa-88e7-c460f099a9e7)

I can't share the original code but I'll try to create a repo with this behaviour so you can reproduce it. Btw do you want me to create another issue for it?

**Comment by nCrafts** [comment]
We can continue here. The values are not sent via src. We use postmessage, which would fail with very old browsers. Are you seeing this issue with all fields, or only the ones with variables. Also, you should use field IDs (like field1) over field labels.

**Comment by LeonardoRick** [comment]
Ok, thanks!

>  which would fail with very old browsers

Im using chrome in a recent version so I don't think that should be a problem

> Are you seeing this issue with all fields, or only the ones with variables.

I don't think I understood your question properly. The problem is with the values that needs to be populated and pre-filled. The other inputs do not have a problem because I don't have a initial value for them.

> Also, you should use field IDs (like field1) over field labels.

I managed to get access to the formcraft editing interface and re-check that I was using the wrong field id. But even using the right one, the value is not being populated at all.

This is the field id: 
![image](https://github.com/user-attachments/assets/f804a69f-ed91-4d26-a79a-b8f978622d71)
code: 
```javascript
      if (this.formcraftsForm) {
        // console.log('value will be updated');
        this.formcraftsForm.values({
          field30: 'test udpated',
        });
      } else {
        // console.log('form initialized');
        this.formcraftsForm = await createPopup({
          form: '<form_key>', // Your form key
          width: 500, // Max width of the form
          redirectWithin: true, // Keep redirect within form frame
          values: {
            field30: 'test initial',
          },
        });
      }
      this.formcraftsForm.open();

```
print: 
![image](https://github.com/user-attachments/assets/b0ec2bf0-a07e-4a5b-ae99-808e2188ea8e)


How it opens: 
![image](https://github.com/user-attachments/assets/0d246130-6e95-4552-9d71-cbbad3e72b1e)

**Comment by LeonardoRick** [comment]
The error was on my side, anyway, thanks for the API! Would be great if we could send the fields using the label names as well.

**Comment by nCrafts** [comment]
Ah, I see. field54 here is the rich text field, which doesn't actually store values at all. This field simply contains text for display. Now this field is referencing another field, also labelled, Customer Name, which is a hidden-type field. You need to find and use the field ID for that field.

**Comment by nCrafts** [comment]
Labels do work when used directly in the URL. Generally, we don't want people to be able to use labels with the library since any change in the field label will then break the embed. Field IDs never change.
